/*
 * Copyright (c) 2017. Helge Stenström
 */

package Helge;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main extends Application {

    /**
     * This method is run automatically by the JavaFx framework.
     * It starts the wine list form, which is the first form the user sees.
     * @param primaryStage
     * @throws Exception
     */
    @Override
    public void start(Stage primaryStage) throws Exception{
        new ListController(primaryStage);
    }


    /**
     * Every program must have a main method, which is the first one that is run. This is it.
     * It is auto generated by the IDE.
     * @param args
     */
    public static void main(String[] args) {
        launch(args);
    }
}
