/*
 * Copyright (c) 2017. Helge Stenström
 */

package Helge;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main extends Application {

    /**
     * This method is run automatically by the JavaFx framework.
     * It starts the wine list form, which is the first form the user sees.
     * @param primaryStage
     * @throws Exception
     */
    @Override
    public void start(Stage primaryStage) throws Exception{
        ListController lc = new ListController(primaryStage);
    }

    /**
     * This method sets up the first window (stage) that the user sees.
     * It's problably placed here by the IDE, but not used any longer.
     * There is a similar method elsewhere that is used instead.
     * @param primaryStage
     * @throws java.io.IOException
     */
    private void setupStage(Stage primaryStage) throws java.io.IOException {
        Parent root = FXMLLoader.load(getClass().getResource("mockups/WineListForm.fxml"));
        primaryStage.setTitle("Vinkällaren");
        primaryStage.setScene(new Scene(root)); //, 300, 275));
        primaryStage.show();
    }


    /**
     * Every program must have a main method, which is the first one that is run. This is it.
     * It is auto generated by the IDE.
     * @param args
     */
    public static void main(String[] args) {
        launch(args);
    }
}
